// <auto-generated />
using System;
using FIGTakeHomeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FIGTakeHomeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FIGTakeHomeAPI.Models.Advisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LicenseExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LicenseState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NPN")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CarrierId");

                    b.ToTable("Advisors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CarrierId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Smith",
                            LicenseExpirationDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseNumber = "LIC-001",
                            LicenseState = "TX",
                            NPN = "NPN1234567",
                            PhoneNumber = "555-123-4567"
                        },
                        new
                        {
                            Id = 2,
                            CarrierId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            LicenseExpirationDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseNumber = "LIC-002",
                            LicenseState = "CA",
                            NPN = "NPN7654321",
                            PhoneNumber = "555-987-6543"
                        },
                        new
                        {
                            Id = 3,
                            CarrierId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "maria.garcia@example.com",
                            FirstName = "Maria",
                            IsActive = true,
                            LastName = "Garcia",
                            LicenseExpirationDate = new DateTime(2027, 3, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            LicenseNumber = "LIC-003",
                            LicenseState = "FL",
                            NPN = "NPN9876543",
                            PhoneNumber = "555-456-7890"
                        });
                });

            modelBuilder.Entity("FIGTakeHomeAPI.Models.Carrier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AMBestRating")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CarrierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NAICCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Carriers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AMBestRating = "A+",
                            CarrierName = "Nationwide",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NAICCode = "23787",
                            PhoneNumber = "800-421-3535",
                            Website = "https://www.nationwide.com"
                        },
                        new
                        {
                            Id = 2,
                            AMBestRating = "A+",
                            CarrierName = "Prudential Financial",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NAICCode = "68241",
                            PhoneNumber = "800-778-2255",
                            Website = "https://www.prudential.com"
                        },
                        new
                        {
                            Id = 3,
                            AMBestRating = "A",
                            CarrierName = "Lincoln Financial Group",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NAICCode = "65676",
                            PhoneNumber = "877-275-5462",
                            Website = "https://www.lfg.com"
                        },
                        new
                        {
                            Id = 4,
                            AMBestRating = "A+",
                            CarrierName = "Pacific Life",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            NAICCode = "67466",
                            PhoneNumber = "800-800-7681",
                            Website = "https://www.pacificlife.com"
                        });
                });

            modelBuilder.Entity("FIGTakeHomeAPI.Models.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdvisorId")
                        .HasColumnType("int");

                    b.Property<int>("CarrierId")
                        .HasColumnType("int");

                    b.Property<decimal>("CommissionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Premium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StatementDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WritingNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdvisorId");

                    b.HasIndex("CarrierId");

                    b.ToTable("Statements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 255.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5100m,
                            StatementDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-01"
                        },
                        new
                        {
                            Id = 2,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 260.00m,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5200m,
                            StatementDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-02"
                        },
                        new
                        {
                            Id = 3,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 265.00m,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5300m,
                            StatementDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-03"
                        },
                        new
                        {
                            Id = 4,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 270.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5400m,
                            StatementDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-04"
                        },
                        new
                        {
                            Id = 5,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 275.00m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5500m,
                            StatementDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-05"
                        },
                        new
                        {
                            Id = 6,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 280.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5600m,
                            StatementDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-06"
                        },
                        new
                        {
                            Id = 7,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 285.00m,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5700m,
                            StatementDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-07"
                        },
                        new
                        {
                            Id = 8,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 290.00m,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5800m,
                            StatementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-08"
                        },
                        new
                        {
                            Id = 9,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 295.00m,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 5900m,
                            StatementDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-09"
                        },
                        new
                        {
                            Id = 10,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 300.00m,
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 6000m,
                            StatementDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-10"
                        },
                        new
                        {
                            Id = 11,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 305.00m,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 6100m,
                            StatementDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-11"
                        },
                        new
                        {
                            Id = 12,
                            AdvisorId = 1,
                            CarrierId = 1,
                            CommissionAmount = 310.00m,
                            CreatedAt = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 6200m,
                            StatementDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A1-12"
                        },
                        new
                        {
                            Id = 13,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 456.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 7600m,
                            StatementDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-01"
                        },
                        new
                        {
                            Id = 14,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 462.00m,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 7700m,
                            StatementDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-02"
                        },
                        new
                        {
                            Id = 15,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 468.00m,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 7800m,
                            StatementDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-03"
                        },
                        new
                        {
                            Id = 16,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 474.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 7900m,
                            StatementDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-04"
                        },
                        new
                        {
                            Id = 17,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 480.00m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8000m,
                            StatementDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-05"
                        },
                        new
                        {
                            Id = 18,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 486.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8100m,
                            StatementDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-06"
                        },
                        new
                        {
                            Id = 19,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 492.00m,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8200m,
                            StatementDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-07"
                        },
                        new
                        {
                            Id = 20,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 498.00m,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8300m,
                            StatementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-08"
                        },
                        new
                        {
                            Id = 21,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 504.00m,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8400m,
                            StatementDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-09"
                        },
                        new
                        {
                            Id = 22,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 510.00m,
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8500m,
                            StatementDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-10"
                        },
                        new
                        {
                            Id = 23,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 516.00m,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8600m,
                            StatementDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-11"
                        },
                        new
                        {
                            Id = 24,
                            AdvisorId = 1,
                            CarrierId = 2,
                            CommissionAmount = 522.00m,
                            CreatedAt = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8700m,
                            StatementDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-A2-12"
                        },
                        new
                        {
                            Id = 25,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 726.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12100m,
                            StatementDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-01"
                        },
                        new
                        {
                            Id = 26,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 732.00m,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12200m,
                            StatementDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-02"
                        },
                        new
                        {
                            Id = 27,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 738.00m,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12300m,
                            StatementDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-03"
                        },
                        new
                        {
                            Id = 28,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 744.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12400m,
                            StatementDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-04"
                        },
                        new
                        {
                            Id = 29,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 750.00m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12500m,
                            StatementDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-05"
                        },
                        new
                        {
                            Id = 30,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 756.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12600m,
                            StatementDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-06"
                        },
                        new
                        {
                            Id = 31,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 762.00m,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12700m,
                            StatementDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-07"
                        },
                        new
                        {
                            Id = 32,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 768.00m,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12800m,
                            StatementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-08"
                        },
                        new
                        {
                            Id = 33,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 774.00m,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12900m,
                            StatementDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-09"
                        },
                        new
                        {
                            Id = 34,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 780.00m,
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 13000m,
                            StatementDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-10"
                        },
                        new
                        {
                            Id = 35,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 786.00m,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 13100m,
                            StatementDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-11"
                        },
                        new
                        {
                            Id = 36,
                            AdvisorId = 2,
                            CarrierId = 2,
                            CommissionAmount = 792.00m,
                            CreatedAt = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 13200m,
                            StatementDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B1-12"
                        },
                        new
                        {
                            Id = 37,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 405.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8100m,
                            StatementDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-01"
                        },
                        new
                        {
                            Id = 38,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 410.00m,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8200m,
                            StatementDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-02"
                        },
                        new
                        {
                            Id = 39,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 415.00m,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8300m,
                            StatementDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-03"
                        },
                        new
                        {
                            Id = 40,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 420.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8400m,
                            StatementDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-04"
                        },
                        new
                        {
                            Id = 41,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 425.00m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8500m,
                            StatementDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-05"
                        },
                        new
                        {
                            Id = 42,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 430.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8600m,
                            StatementDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-06"
                        },
                        new
                        {
                            Id = 43,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 435.00m,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8700m,
                            StatementDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-07"
                        },
                        new
                        {
                            Id = 44,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 440.00m,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8800m,
                            StatementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-08"
                        },
                        new
                        {
                            Id = 45,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 445.00m,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 8900m,
                            StatementDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-09"
                        },
                        new
                        {
                            Id = 46,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 450.00m,
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 9000m,
                            StatementDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-10"
                        },
                        new
                        {
                            Id = 47,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 455.00m,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 9100m,
                            StatementDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-11"
                        },
                        new
                        {
                            Id = 48,
                            AdvisorId = 2,
                            CarrierId = 3,
                            CommissionAmount = 460.00m,
                            CreatedAt = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 9200m,
                            StatementDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-B2-12"
                        },
                        new
                        {
                            Id = 49,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 528.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 9600m,
                            StatementDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-01"
                        },
                        new
                        {
                            Id = 50,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 533.50m,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 9700m,
                            StatementDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-02"
                        },
                        new
                        {
                            Id = 51,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 539.00m,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 9800m,
                            StatementDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-03"
                        },
                        new
                        {
                            Id = 52,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 544.50m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 9900m,
                            StatementDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-04"
                        },
                        new
                        {
                            Id = 53,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 550.00m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10000m,
                            StatementDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-05"
                        },
                        new
                        {
                            Id = 54,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 555.50m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10100m,
                            StatementDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-06"
                        },
                        new
                        {
                            Id = 55,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 561.00m,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10200m,
                            StatementDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-07"
                        },
                        new
                        {
                            Id = 56,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 566.50m,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10300m,
                            StatementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-08"
                        },
                        new
                        {
                            Id = 57,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 572.00m,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10400m,
                            StatementDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-09"
                        },
                        new
                        {
                            Id = 58,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 577.50m,
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10500m,
                            StatementDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-10"
                        },
                        new
                        {
                            Id = 59,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 583.00m,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10600m,
                            StatementDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-11"
                        },
                        new
                        {
                            Id = 60,
                            AdvisorId = 3,
                            CarrierId = 3,
                            CommissionAmount = 588.50m,
                            CreatedAt = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 10700m,
                            StatementDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C1-12"
                        },
                        new
                        {
                            Id = 61,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 666.00m,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11100m,
                            StatementDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-01"
                        },
                        new
                        {
                            Id = 62,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 672.00m,
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11200m,
                            StatementDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-02"
                        },
                        new
                        {
                            Id = 63,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 678.00m,
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11300m,
                            StatementDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-03"
                        },
                        new
                        {
                            Id = 64,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 684.00m,
                            CreatedAt = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11400m,
                            StatementDate = new DateTime(2026, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-04"
                        },
                        new
                        {
                            Id = 65,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 690.00m,
                            CreatedAt = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11500m,
                            StatementDate = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-05"
                        },
                        new
                        {
                            Id = 66,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 696.00m,
                            CreatedAt = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11600m,
                            StatementDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-06"
                        },
                        new
                        {
                            Id = 67,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 702.00m,
                            CreatedAt = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11700m,
                            StatementDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-07"
                        },
                        new
                        {
                            Id = 68,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 708.00m,
                            CreatedAt = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11800m,
                            StatementDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-08"
                        },
                        new
                        {
                            Id = 69,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 714.00m,
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 11900m,
                            StatementDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-09"
                        },
                        new
                        {
                            Id = 70,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 720.00m,
                            CreatedAt = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12000m,
                            StatementDate = new DateTime(2026, 10, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-10"
                        },
                        new
                        {
                            Id = 71,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 726.00m,
                            CreatedAt = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12100m,
                            StatementDate = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-11"
                        },
                        new
                        {
                            Id = 72,
                            AdvisorId = 3,
                            CarrierId = 4,
                            CommissionAmount = 732.00m,
                            CreatedAt = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Premium = 12200m,
                            StatementDate = new DateTime(2026, 12, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            WritingNumber = "WN-C2-12"
                        });
                });

            modelBuilder.Entity("FIGTakeHomeAPI.Models.Advisor", b =>
                {
                    b.HasOne("FIGTakeHomeAPI.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrier");
                });

            modelBuilder.Entity("FIGTakeHomeAPI.Models.Statement", b =>
                {
                    b.HasOne("FIGTakeHomeAPI.Models.Advisor", "Advisor")
                        .WithMany()
                        .HasForeignKey("AdvisorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FIGTakeHomeAPI.Models.Carrier", "Carrier")
                        .WithMany()
                        .HasForeignKey("CarrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advisor");

                    b.Navigation("Carrier");
                });
#pragma warning restore 612, 618
        }
    }
}
